[package]
name = "hbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
pulldown-cmark = "0.9.3"
time = { version = "0.3.30", features = ["macros", "parsing"] }
url = "2.4.1"
